# Generated by Django 6.0.6 on 2026-06-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingcheckout',
            name='status_token',
            field=models.CharField(db_index=True, default='', max_length=128),
        ),
    ]
