# Generated by Django 6.0.6 on 2026-06-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_processedwebhookevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnsiteOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("checkout_ref", models.CharField(max_length=100, unique=True)),
                ("status_token", models.CharField(db_index=True, default="", max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("line_items", models.JSONField(blank=True, default=list)),
                ("amount_total_cents", models.PositiveIntegerField(default=0)),
                ("currency", models.CharField(default="EUR", max_length=8)),
                ("customer_name", models.CharField(blank=True, default="", max_length=150)),
                ("customer_email", models.EmailField(blank=True, default="", max_length=254)),
                ("payment_intent_id", models.CharField(blank=True, db_index=True, default="", max_length=128)),
                ("payment_client_secret", models.CharField(blank=True, default="", max_length=255)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessedStripeEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.CharField(max_length=128, unique=True)),
                ("event_type", models.CharField(blank=True, default="", max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
