# Generated by Django 6.0.6 on 2026-06-30 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_onsiteorder_processedstripeevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title', 'handle'],
            },
        ),
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_product_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('shopify_variant_id', models.CharField(max_length=255, unique=True)),
                ('variant_title', models.CharField(blank=True, default='', max_length=200)),
                ('handle', models.SlugField(max_length=160, unique=True)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('image_alt', models.CharField(blank=True, default='', max_length=255)),
                ('price_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency_code', models.CharField(default='EUR', max_length=8)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.catalogcollection')),
            ],
            options={
                'ordering': ['sort_order', 'title', 'handle'],
            },
        ),
    ]
