# Generated by Django 6.0.6 on 2026-07-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_update_inspection_report_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='decommissioned_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('retired', 'Retired'), ('decommissioned', 'Decommissioned')], default='active', max_length=20),
        ),
    ]
