# Generated by Django 6.0.6 on 2026-07-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_reportimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('engineer', 'Engineer'), ('office_staff', 'Office Staff'), ('staff', 'Staff'), ('owner', 'Owner')], default='customer', max_length=20),
        ),
    ]
