# Generated by Django 6.0.6 on 2026-07-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='required_password_change',
            field=models.BooleanField(default=False),
        ),
    ]
