# Generated by Django 6.0.6 on 2026-07-15 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_certificate_soft_delete'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='certificate',
            new_name='api_certifi_company_282caa_idx',
            old_name='api_certifi_company_454d1c_idx',
        ),
        migrations.RenameIndex(
            model_name='certificate',
            new_name='api_certifi_recover_ad834f_idx',
            old_name='api_certifi_recover_4bf919_idx',
        ),
    ]
