# Generated by Django 6.0.6 on 2026-07-15 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_site_and_equipment_site'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='equipment',
            new_name='api_equipme_company_817c7b_idx',
            old_name='api_equipme_compan_95d5d7_idx',
        ),
        migrations.RenameIndex(
            model_name='inspectionreport',
            new_name='api_inspect_equipme_3dbb91_idx',
            old_name='api_insprep_equ_del_upd_idx',
        ),
    ]
