# Generated by Django 6.0.6 on 2026-07-29 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auth_user_email_ci_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountActionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('verify_email', 'Verify email'), ('password_reset', 'Password reset'), ('email_change', 'Email change')], max_length=32)),
                ('token_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('issued_for_email', models.EmailField(max_length=254)),
                ('target_email', models.EmailField(max_length=254)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_action_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('consumed_at__isnull', True), ('revoked_at__isnull', True)), fields=('user', 'purpose'), name='unique_active_account_action')],
            },
        ),
    ]
