# Generated by Django 6.0.6 on 2026-07-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_accountsecuritystate'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercecustomerprofile',
            name='verified_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
