# Generated by Django 6.0.6 on 2026-07-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_accountsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercecustomerprofile',
            name='activation_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commercecustomerprofile',
            name='privacy_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='commercecustomerprofile',
            name='privacy_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercecustomerprofile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercecustomerprofile',
            name='terms_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
