# Generated by Django 6.0.6 on 2026-08-05 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_commercecustomerprofile_activation_pending_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='onsiteorder',
            name='shipping_address_line_1',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='onsiteorder',
            name='shipping_address_line_2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='onsiteorder',
            name='shipping_city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='onsiteorder',
            name='shipping_country_code',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='onsiteorder',
            name='shipping_county',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='onsiteorder',
            name='shipping_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='onsiteorder',
            name='shipping_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='onsiteorder',
            name='shipping_postcode',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='onsiteorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onsite_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SavedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=80)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=150)),
                ('recipient_phone', models.CharField(blank=True, default='', max_length=50)),
                ('address_line_1', models.CharField(blank=True, default='', max_length=200)),
                ('address_line_2', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('county', models.CharField(blank=True, default='', max_length=120)),
                ('postcode', models.CharField(blank=True, default='', max_length=40)),
                ('country_code', models.CharField(blank=True, default='', max_length=2)),
                ('is_default_shipping', models.BooleanField(default=False)),
                ('is_default_billing', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commerce_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_addresses', to='api.commercecustomerprofile')),
            ],
            options={
                'ordering': ['-is_default_shipping', '-created_at', 'id'],
            },
        ),
    ]
