# Generated by Django 6.0.6 on 2026-08-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_onsiteorder_shipping_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsecuritystate',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountsecuritystate',
            name='mfa_pending_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='accountsecuritystate',
            name='mfa_recovery_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='accountsecuritystate',
            name='mfa_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
