# Generated by Django 6.0.6 on 2026-08-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_accountsecuritystate_mfa_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onsiteorder',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, unique=True),
        ),
    ]
