# Generated by Django 6.0.6 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_guestorderclaim"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountsession",
            name="device_fingerprint",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="accountsession",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accountsession",
            name="user_agent",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
    ]
