# Generated by Django 6.0.6 on 2026-08-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_hash_order_capability_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='onsiteorder',
            name='fulfillment_status',
            field=models.CharField(blank=True, choices=[('unfulfilled', 'Unfulfilled'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='onsiteorder',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, max_length=20, null=True),
        ),
    ]
