# Generated by Django 6.0.6 on 2026-08-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='onsiteorder',
            name='discount_cents',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='onsiteorder',
            name='shipping_cents',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onsiteorder',
            name='subtotal_cents',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onsiteorder',
            name='tax_cents',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
