# Generated by Django 6.0.6 on 2026-08-16 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_onsiteorder_discount_cents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogproduct',
            name='available_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='reserved_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('released', 'Released'), ('fulfilled', 'Fulfilled')], db_index=True, default='reserved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_reservations', to='api.onsiteorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='api.catalogproduct')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='api_invento_order_i_48f01b_idx'), models.Index(fields=['product', 'status'], name='api_invento_product_3cd143_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('fulfill', 'Fulfillment'), ('adjust', 'Adjustment'), ('return', 'Return')], db_index=True, max_length=20)),
                ('quantity_change', models.IntegerField()),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='api.onsiteorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='api.catalogproduct')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='api_invento_product_f6f2d6_idx'), models.Index(fields=['transaction_type'], name='api_invento_transac_72ed84_idx')],
            },
        ),
    ]
