# Generated by Django 6.0.6 on 2026-08-16 15:23

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_catalogproduct_available_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogproduct',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='catalogproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('sku__isnull', False)), fields=('sku',), name='catalog_product_unique_nonnull_sku'),
        ),
        migrations.AddConstraint(
            model_name='catalogproduct',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_qty__lte', models.F('available_qty'))), name='catalog_product_reserved_lte_available'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_change', 0), _negated=True), name='inventory_transaction_nonzero_change'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total_cents', django.db.models.expressions.CombinedExpression(models.F('unit_price_cents'), '*', models.F('quantity')))), name='orderitem_line_total_matches_qty'),
        ),
    ]
