# Generated by Django 6.0.6 on 2026-08-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_catalogproduct_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogproduct',
            name='inventory_tracked',
            field=models.BooleanField(default=False),
        ),
    ]
