# Generated by Django 6.0.6 on 2026-08-16 15:32

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_catalogproduct_inventory_tracked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreservation',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations', to='api.onsiteorder'),
        ),
        migrations.AddConstraint(
            model_name='onsiteorder',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_cents__isnull', True), ('discount_cents__isnull', True), ('shipping_cents__isnull', True), ('tax_cents__isnull', True), ('amount_total_cents', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('subtotal_cents'), '-', models.F('discount_cents')), '+', models.F('shipping_cents')), '+', models.F('tax_cents'))), _connector='OR'), name='onsite_order_financial_totals_match'),
        ),
    ]
