# Generated by Django 6.0.6 on 2026-08-16 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_repair_partial_status_backfill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogproduct',
            name='shipping_class',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='stock_policy',
            field=models.CharField(choices=[('untracked', 'Untracked'), ('finite', 'Finite'), ('unavailable', 'Unavailable')], default='untracked', max_length=20),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='tax_code',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='weight_grams',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='onsiteorder',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onsiteorder',
            name='cancellation_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='onsiteorder',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onsite_orders', to='api.company'),
        ),
        migrations.AddField(
            model_name='onsiteorder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onsiteorder',
            name='processing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onsiteorder',
            name='refund_total_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='onsiteorder',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipping_class',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax_code',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='weight_grams',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='onsiteorder',
            constraint=models.CheckConstraint(condition=models.Q(('refund_total_cents__gte', 0)), name='onsite_order_refund_total_nonnegative'),
        ),
    ]
