# Generated by Django 6.0.6 on 2026-08-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_catalogproduct_shipping_class_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='catalogproduct',
            constraint=models.CheckConstraint(condition=models.Q(('stock_policy__in', ['untracked', 'finite', 'unavailable'])), name='catalog_product_stock_policy_valid'),
        ),
    ]
