# Generated by Django 6.0.6 on 2026-08-16 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_catalogproduct_catalog_product_stock_policy_valid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='onsiteorder',
            name='fulfillment_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_onsite_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
