# Generated by Django 6.0.6 on 2026-08-16 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_onsiteorder_fulfillment_actor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='onsiteorder',
            constraint=models.CheckConstraint(condition=models.Q(('refund_total_cents__lte', models.F('amount_total_cents'))), name='onsite_order_refund_lte_total'),
        ),
    ]
