# Generated by Django 6.0.6 on 2026-08-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_onsiteorder_onsite_order_refund_lte_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedstripeevent',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processedstripeevent',
            name='error_message',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='processedstripeevent',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processedstripeevent',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('processed', 'Processed'), ('rejected', 'Rejected'), ('error', 'Error')], db_index=True, default='processing', max_length=20),
        ),
    ]
