# Generated by Django 6.0.6 on 2026-08-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_processedstripeevent_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onsiteorder',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('chargeback', 'Chargeback')], db_index=True, max_length=20, null=True),
        ),
    ]
