# Generated by Django 6.0.6 on 2026-08-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_onsiteorder_status_token_revoked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercecustomerprofile',
            name='deletion_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercecustomerprofile',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
