# Generated by Django 6.0.6 on 2026-08-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_hash_mfa_recovery_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercecustomerprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
