# Generated by Django 6.0.6 on 2026-08-19 15:14

from django.db import migrations, models


def backfill_finite_inventory(apps, schema_editor):
    CatalogProduct = apps.get_model("api", "CatalogProduct")
    CatalogProduct.objects.all().update(
        stock_policy="finite",
        inventory_tracked=True,
    )


def reverse_finite_inventory(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_cookieconsentrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogproduct',
            name='inventory_tracked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='catalogproduct',
            name='stock_policy',
            field=models.CharField(choices=[('untracked', 'Untracked'), ('finite', 'Finite'), ('unavailable', 'Unavailable')], default='finite', max_length=20),
        ),
        migrations.RunPython(backfill_finite_inventory, reverse_finite_inventory),
    ]
