# Generated by Django 6.0.6 on 2026-08-19 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_alter_catalogproduct_inventory_tracked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.catalogproduct')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
