from django.urls import path

from .account_reset_views import (
    PasswordResetCompleteView,
    PasswordResetRequestView,
)
from .account_views import (
    AccountAddressesView,
    AccountOrdersView,
    CommerceRegistrationView,
    ResendVerificationView,
    VerifyEmailView,
    account_bootstrap,
    account_change_email_complete,
    account_change_email_request,
    account_change_password,
    account_claim_order,
    account_delete,
    account_delete_recover,
    account_disable,
    account_export,
    account_logout_all,
    account_mfa_setup,
    account_mfa_verify,
    account_revoke_session,
    account_security_events,
    account_sessions,
)
from .auth_views import PortalTokenObtainPairView, PortalTokenRefreshView
from .consent_views import record_consent, withdraw_consent
from .portal_views import (
    portal_create_customer,
    portal_certificate_delete,
    portal_certificate_download,
    portal_certificate_recover,
    portal_companies,
    portal_company_header,
    portal_company_site_detail,
    portal_company_sites,
    portal_site_certificates,
    portal_site_certificates_generate,
    portal_dashboard_stats,
    portal_equipment_certificates,
    portal_equipment_activity,
    portal_equipment_list,
    portal_equipment_update,
    portal_equipment_reports,
    portal_pending_report_approvals,
    portal_logout,
    portal_me,
    portal_orders,
    portal_report_recover,
    portal_report_owner_edit,
    portal_report_revisions,
    portal_staff_assignments,
)
from .portal_views_modules.catalog import (
    portal_catalog_collection_detail,
    portal_catalog_collection_state,
    portal_catalog_collections,
    portal_catalog_product_adjust_stock,
    portal_catalog_product_detail,
    portal_catalog_product_state,
    portal_catalog_products,
)
from .views import (
    csrf_seed,
    health_check,
    hello,
    onsite_checkout_intent,
    onsite_checkout_status,
    onsite_order_summary,
    readiness_check,
    shop_collection_detail,
    shop_collections,
    shop_featured_products,
    shop_product_detail,
    stripe_webhook,
)

urlpatterns = [
    path("account/bootstrap/", account_bootstrap, name="account_bootstrap"),
    path("account/orders/", AccountOrdersView.as_view(), name="account_orders"),
    path("account/orders/<str:checkout_ref>/", AccountOrdersView.as_view(), name="account_order_detail"),
    path("account/orders/by-number/<str:order_number>/invoice/", AccountOrdersView.as_view(), {"invoice": True}, name="account_order_invoice"),
    path("account/orders/by-number/<str:order_number>/", AccountOrdersView.as_view(), name="account_order_detail_by_number"),
    path("account/addresses/", AccountAddressesView.as_view(), name="account_addresses"),
    path("account/addresses/<int:address_id>/", AccountAddressesView.as_view(), name="account_address_detail"),
    path("account/register/", CommerceRegistrationView.as_view(), name="account_register"),
    path("account/verify-email/", VerifyEmailView.as_view(), name="account_verify_email"),
    path(
        "account/resend-verification/",
        ResendVerificationView.as_view(),
        name="account_resend_verification",
    ),
    path("account/password-reset/", PasswordResetRequestView.as_view(), name="account_password_reset_request"),
    path(
        "account/password-reset/complete/",
        PasswordResetCompleteView.as_view(),
        name="account_password_reset_complete",
    ),
    path("account/change-password/", account_change_password, name="account_change_password"),
    path("account/claim-order/", account_claim_order, name="account_claim_order"),
    path("account/change-email/", account_change_email_request, name="account_change_email_request"),
    path("account/change-email/complete/", account_change_email_complete, name="account_change_email_complete"),
    path("account/disable/", account_disable, name="account_disable"),
    path("account/delete/", account_delete, name="account_delete"),
    path("account/delete/recover/", account_delete_recover, name="account_delete_recover"),
    path("account/export/", account_export, name="account_export"),
    path("account/mfa/setup/", account_mfa_setup, name="account_mfa_setup"),
    path("account/mfa/verify/", account_mfa_verify, name="account_mfa_verify"),
    path("account/security-events/", account_security_events, name="account_security_events"),
    path("account/sessions/", account_sessions, name="account_sessions"),
    path("account/sessions/<str:session_id>/revoke/", account_revoke_session, name="account_revoke_session"),
    path("account/logout-all/", account_logout_all, name="account_logout_all"),
    path("consent/record/", record_consent),
    path("consent/withdraw/", withdraw_consent),
    path("auth/token/", PortalTokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("auth/token/refresh/", PortalTokenRefreshView.as_view(), name="token_refresh"),
    path("auth/logout/", portal_logout),
    path("portal/me/", portal_me),
    path("portal/orders/", portal_orders),
    path("portal/orders/<str:order_number>/", portal_orders),
    path("portal/catalog/products/", portal_catalog_products),
    path("portal/catalog/collections/", portal_catalog_collections),
    path("portal/catalog/collections/<int:collection_id>/", portal_catalog_collection_detail),
    path("portal/catalog/collections/<int:collection_id>/state/", portal_catalog_collection_state),
    path("portal/catalog/products/<int:product_id>/", portal_catalog_product_detail),
    path("portal/catalog/products/<int:product_id>/state/", portal_catalog_product_state),
    path("portal/catalog/products/<int:product_id>/stock/", portal_catalog_product_adjust_stock),
    path("portal/companies/", portal_companies),
    path("portal/dashboard-stats/", portal_dashboard_stats),
    path("portal/customers/", portal_create_customer),
    path("portal/company-header/", portal_company_header),
    path("portal/company-sites/", portal_company_sites),
    path("portal/company-sites/<int:site_id>/", portal_company_site_detail),
    path("portal/company-sites/<int:site_id>/certificates/", portal_site_certificates),
    path("portal/company-sites/<int:site_id>/certificates/generate/", portal_site_certificates_generate),
    path("portal/equipment/", portal_equipment_list),
    path("portal/equipment/<int:equipment_id>/", portal_equipment_update),
    path("portal/equipment/<int:equipment_id>/activity/", portal_equipment_activity),
    path("portal/equipment/<int:equipment_id>/reports/", portal_equipment_reports),
    path("portal/pending-report-approvals/", portal_pending_report_approvals),
    path("portal/reports/<int:report_id>/", portal_report_owner_edit),
    path("portal/reports/<int:report_id>/recover/", portal_report_recover),
    path("portal/reports/<int:report_id>/revisions/", portal_report_revisions),
    path("portal/equipment/<int:equipment_id>/certificates/", portal_equipment_certificates),
    path("portal/certificates/<int:certificate_id>/", portal_certificate_delete),
    path("portal/certificates/<int:certificate_id>/recover/", portal_certificate_recover),
    path("portal/certificates/<int:certificate_id>/download/", portal_certificate_download),
    path("portal/staff-assignments/", portal_staff_assignments),
    path("hello/", hello),
    path("health/", health_check),
    path("ready/", readiness_check),
    path("csrf/", csrf_seed),
    path("shop/products/featured/", shop_featured_products),
    path("shop/products/<str:handle>/", shop_product_detail),
    path("shop/collections/", shop_collections),
    path("shop/collections/<str:handle>/", shop_collection_detail),
    path("payments/onsite-intent/", onsite_checkout_intent),
    path("payments/onsite-status/", onsite_checkout_status),
    path("payments/onsite-order-summary/", onsite_order_summary),
    path("payments/stripe/webhook/", stripe_webhook),
]
