const keyPart = (value) => value == null ? '' : String(value)

export const queryKeys = {
  catalog: () => ['catalog'],
  collections: (filters = {}) => ['catalog', 'collections', filters],
  collection: (handle) => ['catalog', 'collection', keyPart(handle)],
  products: (filters = {}) => ['catalog', 'products', filters],
  ownerCatalog: (filters = {}) => ['owner-catalog', filters],
  product: (handle) => ['catalog', 'product', keyPart(handle)],
  account: () => ['account'],
  orders: (scope = 'list') => ['account', 'orders', scope],
  portalCustomerOrders: () => ['portal-customer-orders'],
  portalProfile: () => ['portal-profile'],
  portalCompanies: () => ['portal-companies'],
  portalCompanyHeader: (companyId) => ['portal-company-header', keyPart(companyId)],
  portalEquipment: ({ companyId = '', siteId = '', search = '' } = {}) => [
    'portal-equipment',
    keyPart(companyId),
    keyPart(siteId),
    keyPart(search),
  ],
  portalReports: (equipmentId) => ['portal-reports', keyPart(equipmentId)],
  portalReportsRoot: () => ['portal-reports'],
  portalEquipmentActivity: (equipmentId) => ['portal-equipment-activity', keyPart(equipmentId)],
  portalEquipmentActivityRoot: () => ['portal-equipment-activity'],
  portalGeneratedCertificates: (siteId) => ['portal-generated-certificates', keyPart(siteId)],
  portalGeneratedCertificatesRoot: () => ['portal-generated-certificates'],
  portalPendingApprovals: (role) => ['portal-pending-approvals', keyPart(role)],
  portalPendingApprovalsRoot: () => ['portal-pending-approvals'],
  portalDashboardStats: (role) => ['portal-dashboard-stats', keyPart(role)],
  portalDashboardStatsRoot: () => ['portal-dashboard-stats'],
  portalStaffAssignments: (status) => ['portal-staff-assignments', keyPart(status)],
  portalStaffAssignmentsRoot: () => ['portal-staff-assignments'],
  portalEquipmentRoot: () => ['portal-equipment'],
  order: (orderNumber) => ['account', 'order', keyPart(orderNumber)],
  addresses: () => ['account', 'addresses'],
  checkout: (checkoutRef) => ['checkout', keyPart(checkoutRef)],
  portalFulfillmentOrders: (bucket = 'recent', page = 1, pageSize = 3) => [
    'portal-fulfillment-orders',
    String(bucket || ''),
    Number(page || 1),
    Number(pageSize || 3),
  ],
  portalOrder: (orderNumber) => ['portal', 'order', keyPart(orderNumber)],
}